# Generated by Django 4.1.4 on 2023-01-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
