# Generated by Django 4.1.4 on 2022-12-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthday_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
